### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Chembampul** [illavaria/TRiTPO_lab2#2]
1. В тексте присутствует пояснение термина "Логин", однако при каждом употреблении этого термина в тексте повторяется и его разъяснение "Вымышленное уникальное имя пользователя". Для соблюдения норм написания документации требуется убрать данные повторы, т. к. при написании документации, пояснение каждому термину даётся единожды. То же самое правило требуется применить и к остальным терминам в тексте.
2. Пункты 2.3.2.1 и 2.3.2.2 правильнее было бы объединить в один по той причине, что в этих 2 пунктах по итогу перечислены все возрастные группы людей, то есть разбиение заголовка 2.3.2 на 2 подпункта не несёт какой-либо дополнительной информации и никак логически не обосновано.

**Comment by illavaria** [comment]
Первый недочет был исправлен. 
Со вторым пунктом я согласна не полностью, так как целью создания двух различных подпунктов является разбиение аудитории на целевую и побочную, а не просто перечисление возрастных групп пользователей.
